### ISSUE TITLE
Logowanie dostępu do CLI kluczem SSH z agenta

### ISSUE THREAD

**Issue by kbiernat** [hyperonecom/h1-cli#2]
Dzień dobry,
proponuję dodać logowanie użycia klucza SSH z ssh-agenta jako skuteczną metodą autoryzacji do h1 login <username>.
Wielkie było moje zdziwienie, gdy po 1. h1 login <username> zadziałało bez podawania jakichkolwiek haseł,
A po 2, gdy zalogowałem się na zewnętrzny serwer (z innym kluczem, jednak ten dodany przez panel był już odblokowany) i udało mi się uzyskać dostęp przez CLI.

**Comment by gregorybrzeski** [comment]
> proponuję dodać logowanie użycia klucza SSH z ssh-agenta jako skuteczną metodą autoryzacji do h1 login .

Czy mógłbyś wyjaśnić co masz na myśli ?

**Comment by kbiernat** [comment]
$ ./h1-cli-linux login krzysztof.biernat@example.pl                                                                                                                                      
info: You successfully logged and stored your apiKey in config file

brakuje mi tu informacji, że użyto klucza SSH o takim i takim id/opisie/fingerprincie/czymkolwiek w celu zalogowania jako użytkownik X.
W pierwszej chwili przestraszyłem się, że jest jakaś dziura w h1 login i po prostu puszcza użytkownika po samym loginie.

**Comment by gregorybrzeski** [comment]
Wszystko jasne, cenna uwaga. Dodamy odpowiednią informację, a także zawsze PR są mile widziane :-)

**Comment by ad-m** [comment]
@gregorybrzeski , zdaje się brak jest odpowiedniego komunikatu, że został wzięty klucz SSH. Nie jest to typowe zachowanie, więc wypada dać komunikat. Obecnie:
``` 
$ h1 login karol.bregula@siecobywatelska.pl
info: You successfully logged and stored your apiKey in config file
```
Inaczej wygląda to bardzo groźnie, że można się logować bez hasła 😉

**Comment by gregorybrzeski** [comment]
Klucze ssh pozwalają na zalogowanie się bez hasła jest to typowe zachowanie w działaniu narzędzi na przykład takich jak "git" :) Cenna uwaga dotyczące dodatkowej informacji na ten temat zostanie uwzględniona.

@kbiernat w przypadku korzystania z kluczy ssh nie ma potrzeby wykonywania ./h1 login <username> wystarczy od razu wykonywać komendę, automatycznie zostanie dokonane uzyskanie api-key jeśli będzie potrzeba. Pozwala to na wygodne korzystanie z narzędzia cli. 

Także niedługo będą dostępne "service accounts" które będą pozwalały ograniczyć dostęp do wybranych zasobów, co pozwoli na bezpieczniejszą automatyzację i skryptowanie bez konieczności korzystania z konta które daje dostęp do wszystkich zasobów.

**Comment by ad-m** [comment]
W tym kontekście dodam, że przydałaby się w tym miejscu informacja o aktywnym tenancie.
