### ISSUE TITLE
Trying this out on Windows CLI

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hyperonecom/h1-cli#222]
I tried to follow this example:

![image](https://user-images.githubusercontent.com/15063294/46140623-e383b800-c251-11e8-8ffb-08cfe6003fed.png)

Either I'm using it wrong.... or something is not working

![image](https://user-images.githubusercontent.com/15063294/46140644-f39b9780-c251-11e8-9b18-fd72781e50a6.png)

**Comment by gregorybrzeski** [comment]
@fredericosilva note the openssl error, I'm wondering if it's a matter of something within the packaged binary or on @PrzemyslawKlys system.

**Comment by ad-m** [comment]
@PrzemyslawKlys , command ```h1 firewall tag list``` is not available in latest released version. I believe you are looking on ``develop``` branch, which refers to development version, which are not released yet. See https://github.com/hyperonecom/h1-cli/blob/v1.1.0/docs/firewall.md for documentation for latest released version.

**Comment by fredericosilva** [comment]
@PrzemyslawKlys Do you have `OPENSSL_CONF ` environment variable set?

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/46142687-0e710a80-c258-11e8-81ec-baa431f84ace.png)

The folder doesn't exists thou.

**Comment by fredericosilva** [comment]
Is the error just a warning message or does it limits CLI's functionality?

**Comment by PrzemyslawKlys** [comment]
Just a warning that looks like an error. And when I removed Env and rebooted it's gone. Since its not needed why check for it in first place ? Maybe supress this error?

**Comment by PrzemyslawKlys** [comment]
Since you are delivering full package and don't need the Windows one I would say supress it. Displaying errors or warnings makes sense if it fails for some reason and it's required to work? If you don't need it at all why check for it in the first place?

**Comment by gregorybrzeski** [comment]
@fredericosilva what's your view on this ?

In my opinion we shouldn't fix the problems on host system.

**Comment by fredericosilva** [comment]
@gregorybrzeski I agree, we should respect host configuration, that unfortunately includes host misconfiguration :)
