### ISSUE TITLE
CLI doesn't show where ApiKey is stored

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hyperonecom/h1-cli#224]
Following is returned when you login ... which is fine

![image](https://user-images.githubusercontent.com/15063294/46156296-72f09180-c279-11e8-9816-3b49727a7f38.png)

My problem is I am not informed where it's storing this key. Additionally if API key is generated I would assume from now on I can take that key and start using it authenticate in my scripts. Otherwise I need to use login and password each time. I am aware of SSH ability just not using it.

**Comment by ad-m** [comment]
It looks like we should clarify this message. This API key is for temporary use only. Its operation is similar to the session identifier.

If you want to use the tool in scripts, you should use the service account - run ```h1 project token --help``` for details.

**Comment by PrzemyslawKlys** [comment]
I think you should clarify it more. You’re telling people you are storing this in a config file. Which begs for a question where? Either rephrase it so that people don’t search for mysterious config file or tell then where it is :-)

**Comment by ad-m** [comment]
@PrzemyslawKlys the user does not have to modify and read the configuration file by himself. 

Location of config file is documented at https://github.com/hyperonecom/h1-cli/blob/master/README.md#u%C5%BCycie .
