### ISSUE TITLE
h1 env - same values

### ISSUE THREAD

**Issue by gregorybrzeski** [hyperonecom/h1-cli#362]
https://github.com/hyperonecom/h1-cli/blob/master/bin/env/index.js#L42-L43

Two env variables are set in here:

- (scope)_ACCESS_TOKEN_ID
- (scope) _ACCESS_TOKEN_SECRET

They are set to have the same value in both cases, the apiKey from profile.

Is that correct ? If it's correct then why do we have two different env vars ?

**Comment by ad-m** [comment]
HyperOne has developed a new version of CLI v2 which is a complete rewrite of this software. The problem you indicated concerns the V1 version, which is not further developed. The reported problem should no longer exist in V2, especially due authentication methods implemented in API v2. 

Feel free to ask if you have additional comments.
