### ISSUE TITLE
h1 env project select is not working

### ISSUE THREAD

**Issue by fredericosilva** [hyperonecom/h1-cli#405]
```
eval $(h1 env --project-select 5d516a2xxxxxxxxxxxxxxxxxx)
eval $(h1 env --project 5d516a2xxxxxxxxxxxxxxxxxx)
```
What should those options do?

**Comment by ad-m** [comment]
HyperOne has developed a new version of CLI v2 which is a complete rewrite of this software. The problem you indicated concerns the V1 version, which is not further developed. The reported problem should no longer exist in V2. I have confirmed that `h1 env` command no longer exists in CLI v2 due authentication methods of API v2.

Feel free to ask if you have additional comments.
