### ISSUE TITLE
docs: firewall broken examples

### ISSUE THREAD

**Issue by fredericosilva** [hyperonecom/h1-cli#56]
Something seems to be broken on the examples generation.

```bash
h1 firewall ingress add --firewall secure-zone-fw --action allow 
--priority 300 
--filter tcp:80 \ --external 0.0.0.0/0 --internal 10.177.2.2 
--name 'Allow HTTP'
```

eg: https://github.com/hyperonecom/h1-cli/blob/develop/docs/firewall.md#add-firewall-to-allow-any-incoming-http-traffic-to-1017722

**Comment by ad-m** [comment]
Fixed via #63
