### ISSUE TITLE
Update "h1 vm queue" to "h1 vm history"

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#60]

**Comment by ad-m** [comment]
It requires the first change on the API side so that the API contains a real activity history (asynchronous and synchronous) according to the users' expectations.

**Comment by gregorybrzeski** [comment]
I would like to disagree, as currently async requests are already returned. Sync requests are going to be returned in near future and their format is going to be same as async ones.

Therefore is there anything what's stopping us from implementing `history` before async events are going to be available as well ?
