### ISSUE TITLE
Empty line if no result

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#69]
When there is no result there is still empty line in output. For example if there is no disk I got following result:
```
$ h1 disk list --output tsv --project-select 5af0bbbcb7802508ad844caa --query '[].{id: _id}' | wc -l
1
```

This affects scripting, e.g. when using xargs.
```
$ h1 disk list --output tsv --project-select 5af0bbbcb7802508ad844caa --query '[].{id: _id}' | xargs -n 1 -P 8 h1 disk delete --yes --iso
usage: h1 disk delete [-h] [--output {table,tsv,list,json}] [--query QUERY]
                      [--transform TRANSFORM] --disk DISK
                      [--project-select PROJECT-SELECT] [--verbose] [--no-wait]
                      [--dry-run] [--yes]
                      
h1 disk delete: error: Argument "--disk" is required
```

**Comment by fredericosilva** [comment]
It seems to be fixed on master. Can you confirm @ad-m ?

**Comment by ad-m** [comment]
Empty response still contains empty rule.

```
$ h1 disk list --output tsv --project-select 5af0bbbcb7802508ad844caa --query '[].{id: _id}' | wc -l
1
```

However, we use a different approach in ```xargs``` scripts and we do not feel it anymore.

**Comment by ad-m** [comment]
HyperOne has developed a new version of CLI v2 which is a complete rewrite of this software. The problem you indicated concerns the V1 version, which is not further developed. The reported problem should no longer exist in V2.

Feel free to ask if you have additional comments.
