### ISSUE TITLE
Add "history" to all resources

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#76]

**Comment by ad-m** [comment]
There is no reason to provide "tag" for other resources yet. Such use may appear in the future.

Making available the change history of each resource individually (who changed the name of the virtual machine?) and collectively for the tenant (who deleted the virtual machine?) can be useful. AWS provides https://aws.amazon.com/cloudtrail/ . Heroku provides the history of recent activities in the panel and this is very important from the perspective of the user's experience.

**Comment by ad-m** [comment]
Tags are useful for:
- list resources by tag (PROD, DEV) eg. production-ready virtual machine,
- remove resources by tag eg. related to test suite.

**Comment by gregorybrzeski** [comment]
Would you be kind enough to show a use case for `remove resources by tag` and how would it be implemented using CLI ?

**Comment by ad-m** [comment]
These are cases for the use of tags. I do not mean to translate this 1: 1 into a CLI command. Thus, such an operation would be a combination of at least two commands (list and delete). I wrote down because I wrote "Such use may appear in the future.".

**Comment by ad-m** [comment]
Tags are useful to Ansible dynamic inventory too.

**Comment by ad-m** [comment]
@fredericosilva , fixed via #82?

**Comment by fredericosilva** [comment]
yes
