### ISSUE TITLE
Available values of "--image"

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#78]
What are available values for ```--image```? In which way values are resolved?

Yesterday shows me that following commands works:
```
h1 vm create --name test-vm2 --os-disk os-disk-0,ssd,10 --type a1.nano --ssh so-wp --image debian
```
In some way ```--image``` have some name resolution, but it's not clear how it works.

**Comment by fredericosilva** [comment]
@ad-m  VM creation image parameter has the following format `--image [<distro>[:<release>] || name || id]` where `distro:release` is from recommended images.

**Comment by ad-m** [comment]
I asked the question because I needed this information. I needed this information because I see the potential to optimize tests and update the documentation.
